//
// Generated file, do not edit! Created by opp_msgtool 6.3 from msg/AlertMsg.msg.
//

#ifndef __DPCRIDS_ALERTMSG_M_H
#define __DPCRIDS_ALERTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace dpcrids {

class AlertMsg;

}  // namespace dpcrids


namespace dpcrids {

/**
 * Class generated from <tt>msg/AlertMsg.msg:8</tt> by opp_msgtool.
 * <pre>
 * message AlertMsg
 * {
 *     string decision;             // "NORMAL", "ATTACK", "ESCALATE"
 *     string path;                 // "fast", "heavy", "fail_open", "gateway"
 *     double pAttackRaw;
 *     double pAttackCalibrated;
 *     double latencyMs;
 *     bool escalateFlag;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class AlertMsg : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string decision;
    ::omnetpp::opp_string path;
    double pAttackRaw = 0;
    double pAttackCalibrated = 0;
    double latencyMs = 0;
    bool escalateFlag = false;
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const AlertMsg& other);

  protected:
    bool operator==(const AlertMsg&) = delete;

  public:
    AlertMsg(const char *name=nullptr, short kind=0);
    AlertMsg(const AlertMsg& other);
    virtual ~AlertMsg();
    AlertMsg& operator=(const AlertMsg& other);
    virtual AlertMsg *dup() const override {return new AlertMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDecision() const;
    virtual void setDecision(const char * decision);

    virtual const char * getPath() const;
    virtual void setPath(const char * path);

    virtual double getPAttackRaw() const;
    virtual void setPAttackRaw(double pAttackRaw);

    virtual double getPAttackCalibrated() const;
    virtual void setPAttackCalibrated(double pAttackCalibrated);

    virtual double getLatencyMs() const;
    virtual void setLatencyMs(double latencyMs);

    virtual bool getEscalateFlag() const;
    virtual void setEscalateFlag(bool escalateFlag);

    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlertMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlertMsg& obj) {obj.parsimUnpack(b);}


}  // namespace dpcrids


namespace omnetpp {

template<> inline dpcrids::AlertMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<dpcrids::AlertMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DPCRIDS_ALERTMSG_M_H

