//
// Generated file, do not edit! Created by opp_msgtool 6.3 from msg/CanFrameMsg.msg.
//

#ifndef __DPCRIDS_CANFRAMEMSG_M_H
#define __DPCRIDS_CANFRAMEMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace dpcrids {

class CanFrameMsg;

}  // namespace dpcrids


namespace dpcrids {

/**
 * Class generated from <tt>msg/CanFrameMsg.msg:8</tt> by opp_msgtool.
 * <pre>
 * message CanFrameMsg
 * {
 *     int canId;
 *     int dlc;
 *     int data[8];             // payload bytes d0..d7 (0-255)
 *     int label = -1;          // ground truth: 0=normal, 1=attack, -1=unknown
 *     string attackType = "";  // "normal", "dos", "fuzzy", "gear", "rpm"
 * }
 * </pre>
 */
class CanFrameMsg : public ::omnetpp::cMessage
{
  protected:
    int canId = 0;
    int dlc = 0;
    int data[8] = {0};
    int label = -1;
    ::omnetpp::opp_string attackType = "";

  private:
    void copy(const CanFrameMsg& other);

  protected:
    bool operator==(const CanFrameMsg&) = delete;

  public:
    CanFrameMsg(const char *name=nullptr, short kind=0);
    CanFrameMsg(const CanFrameMsg& other);
    virtual ~CanFrameMsg();
    CanFrameMsg& operator=(const CanFrameMsg& other);
    virtual CanFrameMsg *dup() const override {return new CanFrameMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getCanId() const;
    virtual void setCanId(int canId);

    virtual int getDlc() const;
    virtual void setDlc(int dlc);

    virtual size_t getDataArraySize() const;
    virtual int getData(size_t k) const;
    virtual void setData(size_t k, int data);

    virtual int getLabel() const;
    virtual void setLabel(int label);

    virtual const char * getAttackType() const;
    virtual void setAttackType(const char * attackType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CanFrameMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CanFrameMsg& obj) {obj.parsimUnpack(b);}


}  // namespace dpcrids


namespace omnetpp {

template<> inline dpcrids::CanFrameMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<dpcrids::CanFrameMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DPCRIDS_CANFRAMEMSG_M_H

