//
// Generated file, do not edit! Created by opp_msgtool 6.3 from msg/EthFrameMsg.msg.
//

#ifndef __DPCRIDS_ETHFRAMEMSG_M_H
#define __DPCRIDS_ETHFRAMEMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace dpcrids {

class EthFrameMsg;

}  // namespace dpcrids


namespace dpcrids {

/**
 * Class generated from <tt>msg/EthFrameMsg.msg:8</tt> by opp_msgtool.
 * <pre>
 * message EthFrameMsg
 * {
 *     int payload[];           // variable-length payload bytes (0-255)
 *     int payloadLength;
 *     string srcAddress = "";
 *     string dstAddress = "";
 *     int label = -1;          // ground truth: 0=normal, 1=attack
 *     string attackType = "";
 *     string protocol = "";    // e.g. "SOME/IP", "DoIP", "AVB"
 * }
 * </pre>
 */
class EthFrameMsg : public ::omnetpp::cMessage
{
  protected:
    int *payload = nullptr;
    size_t payload_arraysize = 0;
    int payloadLength = 0;
    ::omnetpp::opp_string srcAddress = "";
    ::omnetpp::opp_string dstAddress = "";
    int label = -1;
    ::omnetpp::opp_string attackType = "";
    ::omnetpp::opp_string protocol = "";

  private:
    void copy(const EthFrameMsg& other);

  protected:
    bool operator==(const EthFrameMsg&) = delete;

  public:
    EthFrameMsg(const char *name=nullptr, short kind=0);
    EthFrameMsg(const EthFrameMsg& other);
    virtual ~EthFrameMsg();
    EthFrameMsg& operator=(const EthFrameMsg& other);
    virtual EthFrameMsg *dup() const override {return new EthFrameMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setPayloadArraySize(size_t size);
    virtual size_t getPayloadArraySize() const;
    virtual int getPayload(size_t k) const;
    virtual void setPayload(size_t k, int payload);
    virtual void insertPayload(size_t k, int payload);
    [[deprecated]] void insertPayload(int payload) {appendPayload(payload);}
    virtual void appendPayload(int payload);
    virtual void erasePayload(size_t k);

    virtual int getPayloadLength() const;
    virtual void setPayloadLength(int payloadLength);

    virtual const char * getSrcAddress() const;
    virtual void setSrcAddress(const char * srcAddress);

    virtual const char * getDstAddress() const;
    virtual void setDstAddress(const char * dstAddress);

    virtual int getLabel() const;
    virtual void setLabel(int label);

    virtual const char * getAttackType() const;
    virtual void setAttackType(const char * attackType);

    virtual const char * getProtocol() const;
    virtual void setProtocol(const char * protocol);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthFrameMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthFrameMsg& obj) {obj.parsimUnpack(b);}


}  // namespace dpcrids


namespace omnetpp {

template<> inline dpcrids::EthFrameMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<dpcrids::EthFrameMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DPCRIDS_ETHFRAMEMSG_M_H

