//
// Generated file, do not edit! Created by opp_msgtool 6.3 from msg/ExpertOutput.msg.
//

#ifndef __DPCRIDS_EXPERTOUTPUT_M_H
#define __DPCRIDS_EXPERTOUTPUT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace dpcrids {

class ExpertOutput;

}  // namespace dpcrids


namespace dpcrids {

/**
 * Class generated from <tt>msg/ExpertOutput.msg:9</tt> by opp_msgtool.
 * <pre>
 * message ExpertOutput
 * {
 *     string protocol;           // "can" or "ethernet"
 *     double logit;              // raw model logit
 *     double rawProb;            // sigmoid(logit)
 *     double calibratedProb;     // temperature-scaled probability
 *     double embedding[128];     // 128-dim feature embedding
 *     simtime_t timestamp;       // simulation time of the input data
 * }
 * </pre>
 */
class ExpertOutput : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string protocol;
    double logit = 0;
    double rawProb = 0;
    double calibratedProb = 0;
    double embedding[128] = {0};
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const ExpertOutput& other);

  protected:
    bool operator==(const ExpertOutput&) = delete;

  public:
    ExpertOutput(const char *name=nullptr, short kind=0);
    ExpertOutput(const ExpertOutput& other);
    virtual ~ExpertOutput();
    ExpertOutput& operator=(const ExpertOutput& other);
    virtual ExpertOutput *dup() const override {return new ExpertOutput(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getProtocol() const;
    virtual void setProtocol(const char * protocol);

    virtual double getLogit() const;
    virtual void setLogit(double logit);

    virtual double getRawProb() const;
    virtual void setRawProb(double rawProb);

    virtual double getCalibratedProb() const;
    virtual void setCalibratedProb(double calibratedProb);

    virtual size_t getEmbeddingArraySize() const;
    virtual double getEmbedding(size_t k) const;
    virtual void setEmbedding(size_t k, double embedding);

    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ExpertOutput& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ExpertOutput& obj) {obj.parsimUnpack(b);}


}  // namespace dpcrids


namespace omnetpp {

template<> inline dpcrids::ExpertOutput *fromAnyPtr(any_ptr ptr) { return check_and_cast<dpcrids::ExpertOutput*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DPCRIDS_EXPERTOUTPUT_M_H

