//
// Generated file, do not edit! Created by opp_msgtool 6.3 from msg/FusionResult.msg.
//

#ifndef __DPCRIDS_FUSIONRESULT_M_H
#define __DPCRIDS_FUSIONRESULT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace dpcrids {

class FusionResult;

}  // namespace dpcrids


namespace dpcrids {

/**
 * Class generated from <tt>msg/FusionResult.msg:9</tt> by opp_msgtool.
 * <pre>
 * message FusionResult
 * {
 *     double logit;              // fused logit
 *     double rawProb;            // sigmoid(fused logit)
 *     double calibratedProb;     // temperature-scaled fused probability
 *     double canRawProb;         // CAN expert's raw probability
 *     double ethRawProb;         // Ethernet expert's raw probability
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class FusionResult : public ::omnetpp::cMessage
{
  protected:
    double logit = 0;
    double rawProb = 0;
    double calibratedProb = 0;
    double canRawProb = 0;
    double ethRawProb = 0;
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const FusionResult& other);

  protected:
    bool operator==(const FusionResult&) = delete;

  public:
    FusionResult(const char *name=nullptr, short kind=0);
    FusionResult(const FusionResult& other);
    virtual ~FusionResult();
    FusionResult& operator=(const FusionResult& other);
    virtual FusionResult *dup() const override {return new FusionResult(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getLogit() const;
    virtual void setLogit(double logit);

    virtual double getRawProb() const;
    virtual void setRawProb(double rawProb);

    virtual double getCalibratedProb() const;
    virtual void setCalibratedProb(double calibratedProb);

    virtual double getCanRawProb() const;
    virtual void setCanRawProb(double canRawProb);

    virtual double getEthRawProb() const;
    virtual void setEthRawProb(double ethRawProb);

    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FusionResult& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FusionResult& obj) {obj.parsimUnpack(b);}


}  // namespace dpcrids


namespace omnetpp {

template<> inline dpcrids::FusionResult *fromAnyPtr(any_ptr ptr) { return check_and_cast<dpcrids::FusionResult*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DPCRIDS_FUSIONRESULT_M_H

